In [43]:
class animal():#构造函数 属性方法 集成 实例可以访问方法属性 子类可以有自己的属性
    def __init__(self,name,kind):
        self.name = name
        self.kind = kind
    def getName(self):
        return self.name
    def getKine(self):
        return self.kind
    def changeName(self,newname):
        self.name = newname

In [3]:
A = animal("cat","cat_kind")

In [4]:
A

In [5]:
dir(A)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'changeName',
 'getKine',
 'getName',
 'kind',
 'name']

In [6]:
A.__class__

__main__.animal

In [7]:
A.__doc__

In [61]:
class animal():
    '''This is doc'''  
    def __init__(self,name,kind):
        self.name = name
        self.kind = kind
    def getName(self):
        '''a method to define the name of the animal'''
        return self.name
    def getKine(self):
        return self.kind
    def changeName(self,newname):
        self.name = newname

In [62]:
A = animal("cat","cat_kind")

In [63]:
A.__doc__

'This is doc'

In [14]:
dir(A.getName)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__func__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [64]:
help(animal)

Help on class animal in module __main__:

class animal(builtins.object)
 |  This is doc
 |  
 |  Methods defined here:
 |  
 |  __init__(self, name, kind)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  changeName(self, newname)
 |  
 |  getKine(self)
 |  
 |  getName(self)
 |      a method to define the name of the animal
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [19]:
print (A)

In [69]:
class animal():
    '''This is doc'''  #缩进要正确
    def __init__(self,name,kind):
        self.name = name
        self.kind = kind
    def getName(self):
        '''a method to define the name of the animal'''
        return self.name
    def getKine(self):
        return self.kind
    def changeName(self,newname):
        self.name = newname
    def __str__(self):
        return (self.name,"---",self.kind)

In [67]:
class animal():
    '''This is doc'''
    def __init__(self, name, kind):
        self.name = name
        self.kind = kind
    def getName(self):
        '''a method to define the name of the animal'''
        return self.name
    def getKine(self):
        return self.kind
    def changeName(self,newname):
        self.name = newname
    def __str__(self):
        return (self.name+''---''+self.kind)

In [24]:
A = animal("cat","cat_kind")

In [25]:
A

In [27]:
print(A)

In [28]:
class cat(animal):
    def __init__():
        pass

In [29]:
class cat_asia(cat):
    def __init__():
        pass

In [30]:
#0303数组切片

In [31]:
from numpy import array

In [32]:
a = array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [33]:
import numpy as np

In [34]:
a[2,3]

23

In [36]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [37]:
a[:,0]#lie

array([ 0, 10, 20, 30, 40, 50])

In [38]:
a[0,:]#hang

array([0, 1, 2, 3, 4, 5])

In [39]:
a[3,:]

array([30, 31, 32, 33, 34, 35])

In [40]:
a[3,2:4]

array([32, 33])

In [41]:
a[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [42]:
a[(0,2,3),::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [30, 32, 34]])

In [51]:
a.max()

55

In [52]:
a.sum()

990

In [54]:
a.mean()#pingjunzhi

27.5

In [55]:
a.std()#biaozhuncha

17.163430115607234

In [56]:
a.var()#fangcha

294.5833333333333

In [70]:
a.any()

True

In [71]:
a = np.zeros(15,15)

TypeError: data type not understood

In [72]:
np.zeros(15,15,dtype=int32)

NameError: name 'int32' is not defined

In [73]:
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting v

In [78]:
a = np.zeros((15,15),dtype=float)

In [79]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [80]:
a[:,0].any()

False

In [81]:
a.any()

False

In [82]:
a = range(1,10)

In [84]:
a

range(1, 10)

In [89]:
a.arange(1,10)

AttributeError: 'range' object has no attribute 'arange'

In [87]:
b=np.zeros((5,5))

In [88]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
b=np.linspace(0,100,5)

In [91]:
b

array([  0.,  25.,  50.,  75., 100.])